from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BROP(object):
    def setupUi(self, BROP):
        BROP.setObjectName("BROP")
        BROP.resize(1160, 828)
        self.centralwidget = QtWidgets.QWidget(BROP)
        self.centralwidget.setObjectName("centralwidget")
        self.operar_consutas = QtWidgets.QTabWidget(self.centralwidget)
        self.operar_consutas.setGeometry(QtCore.QRect(20, 60, 1111, 761))
        self.operar_consutas.setObjectName("operar_consutas")
        self.Operar = QtWidgets.QWidget()
        self.Operar.setObjectName("Operar")
        self.Boton_P_Trait = QtWidgets.QPushButton(self.Operar)
        self.Boton_P_Trait.setGeometry(QtCore.QRect(190, 80, 221, 121))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(22)
        self.Boton_P_Trait.setFont(font)
        self.Boton_P_Trait.setObjectName("Boton_P_Trait")
        self.Boton_RSeg = QtWidgets.QPushButton(self.Operar)
        self.Boton_RSeg.setGeometry(QtCore.QRect(640, 80, 221, 121))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(22)
        self.Boton_RSeg.setFont(font)
        self.Boton_RSeg.setObjectName("Boton_RSeg")
        self.Boton_RComercial = QtWidgets.QPushButton(self.Operar)
        self.Boton_RComercial.setGeometry(QtCore.QRect(410, 460, 221, 121))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(22)
        self.Boton_RComercial.setFont(font)
        self.Boton_RComercial.setObjectName("Boton_RComercial")
        self.label = QtWidgets.QLabel(self.Operar)
        self.label.setGeometry(QtCore.QRect(390, 190, 271, 271))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/Imagen1.png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.operar_consutas.addTab(self.Operar, "")
        self.Consultas = QtWidgets.QWidget()
        self.Consultas.setObjectName("Consultas")
        self.lbl_bbdd = QtWidgets.QLabel(self.Consultas)
        self.lbl_bbdd.setGeometry(QtCore.QRect(40, 30, 221, 21))
        self.lbl_bbdd.setObjectName("lbl_bbdd")
        self.lbl_nombre_tabla = QtWidgets.QLabel(self.Consultas)
        self.lbl_nombre_tabla.setGeometry(QtCore.QRect(40, 60, 211, 31))
        self.lbl_nombre_tabla.setObjectName("lbl_nombre_tabla")
        self.txt_nombre_tabla = QtWidgets.QLineEdit(self.Consultas)
        self.txt_nombre_tabla.setGeometry(QtCore.QRect(240, 60, 221, 22))
        self.txt_nombre_tabla.setObjectName("txt_nombre_tabla")
        self.btn_consultar_datos = QtWidgets.QPushButton(self.Consultas)
        self.btn_consultar_datos.setGeometry(QtCore.QRect(600, 60, 121, 28))
        self.btn_consultar_datos.setObjectName("btn_consultar_datos")
        self.tbl_datos = QtWidgets.QTableWidget(self.Consultas)
        self.tbl_datos.setGeometry(QtCore.QRect(20, 140, 1071, 561))
        self.tbl_datos.setRowCount(2000)
        self.tbl_datos.setColumnCount(80)
        self.tbl_datos.setObjectName("tbl_datos")
        self.Descargar = QtWidgets.QPushButton(self.Consultas)
        self.Descargar.setGeometry(QtCore.QRect(600, 10, 121, 28))
        self.Descargar.setObjectName("Descargar")
        self.label_2 = QtWidgets.QLabel(self.Consultas)
        self.label_2.setGeometry(QtCore.QRect(890, 0, 101, 101))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("img/Imagen1.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.txt_nombre_bbdd = QtWidgets.QLineEdit(self.Consultas)
        self.txt_nombre_bbdd.setGeometry(QtCore.QRect(240, 30, 221, 22))
        self.txt_nombre_bbdd.setObjectName("txt_nombre_bbdd")
        self.operar_consutas.addTab(self.Consultas, "")
        BROP.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BROP)
        self.statusbar.setObjectName("statusbar")
        BROP.setStatusBar(self.statusbar)

        self.retranslateUi(BROP)
        self.operar_consutas.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BROP)

    def retranslateUi(self, BROP):
        _translate = QtCore.QCoreApplication.translate
        BROP.setWindowTitle(_translate("BROP", "BROP"))
        self.Boton_P_Trait.setText(_translate("BROP", "P-trait"))
        self.Boton_RSeg.setText(_translate("BROP", "R(Seg)"))
        self.Boton_RComercial.setText(_translate("BROP", "R Comercial"))
        self.operar_consutas.setTabText(self.operar_consutas.indexOf(self.Operar), _translate("BROP", "Operar"))
        self.lbl_bbdd.setText(_translate("BROP", "<html><head/><body><p>Año a consultar</p></body></html>"))
        self.lbl_nombre_tabla.setText(_translate("BROP", "<html><head/><body><p>Nombre del archivo</p></body></html>"))
        self.btn_consultar_datos.setText(_translate("BROP", "Consultar datos"))
        self.Descargar.setText(_translate("BROP", "Descargar"))
        self.operar_consutas.setTabText(self.operar_consutas.indexOf(self.Consultas), _translate("BROP", "Consultas"))